### ISSUE TITLE
Build fails if mongodb is not present

### ISSUE THREAD

**Issue by VladyslavKurmaz** [attlas/attlas-scraper#21]
## Actual behaviour
> mvn clean install
command generate next output and stuck during timeout
```
2018-07-09 11:40:24.816  INFO 20196 --- [localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:62) ~[mongo-java-driver-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongo-java-driver-3.6.4.jar:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:114) ~[mongo-java-driver-3.6.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_171]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_171]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_171]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:59) ~[mongo-java-driver-3.6.4.jar:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:57) ~[mongo-java-driver-3.6.4.jar:na]
	... 3 common frames omitted

2018-07-09 11:40:25.164  INFO 20196 --- [           main] org.mongodb.driver.cluster               : Cluster description not yet available. Waiting for 30000 ms before timing out
```

## Expected behaviour
* ```mvn clean install``` should not stuck during build
* mongodb connection issue should be catch by our code and print corresponding message
* if connection is missed or lost, service should try to restore connection, timeout should be defined via environment variables

**Comment by fac30ff** [comment]
It's dropped due Class MongoDBconfig where its try to save some entity from commandlinerunner argument for initial startup.

**Comment by VladyslavKurmaz** [comment]
This is detailed doc about DB subsystem intialization
https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html
We can overload next parameter spring.jpa.hibernate.ddl-auto to define expected behavior.

**Comment by VladyslavKurmaz** [comment]
https://stackoverflow.com/questions/34414367/mongo-tries-to-connect-automatically-to-port-27017localhost/34415014
https://stackoverflow.com/questions/28747909/how-to-disable-spring-data-mongodb-autoconfiguration-in-spring-boot
